name: The InBetween
favicon: null
layout_spectrum: 0.17301071877591312
typography_spectrum: 0.20475
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e272c'
    - '#c8cede'
    - '#364f4b'
    - '#678386'
    - '#94a1aa'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
